### ISSUE TITLE
No compatible version found: xlsx@0.8.1

### ISSUE THREAD

**Issue by coolcgp** [weihomechen/vue-mail-front#1]
需要更新xlsx，我在package.jackson更新为"xlsx": "0.10.7"。结果依然不能正常运行，错误情况如下：
![default](https://user-images.githubusercontent.com/9508631/28511268-0dc6d096-707f-11e7-9fb4-89597b4a714f.png)
![default](https://user-images.githubusercontent.com/9508631/28511270-0f07779e-707f-11e7-9fdd-2a9f10305883.png)

**Comment by weihomechen** [comment]
你好，已经修复了，不是依赖的问题，是因为之前把一个图片删了。。。
